loglevel: "debug"
host: "127.0.0.1"
node:
  host: "127.0.0.1"
  port: 8333
  btcd:
    network: 0xd9b4bef9 # mainnet
    agent: "/btcwire:0.5.0/"
    p_version: "70016"
    relay_tx: true
    services: 1
handshake:
  timeout: 30s
