name: Compile and Test
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
        cache: true
    - run: go version

    - name: Compile
      run : make build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          btcd-node-handshake

    - name: Test
      run: make test
    
    - name: Upload Controller Binary
      if: github.event_name == 'push' && (github.branch == 'main' || contains(github.ref, 'refs/tags/'))
      uses: actions/upload-artifact@v3
      with:
        name: btcd-node-handshake
        path: build/btcd-node-handshake